# Generated by Django 4.1.7 on 2023-07-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_info',
            old_name='project_name',
            new_name='name',
        ),
    ]
