# Generated by Django 4.1.7 on 2023-07-31 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0003_alter_project_info_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceiling_finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='仕上 天井')),
            ],
        ),
        migrations.CreateModel(
            name='Floor_finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='仕上 床')),
            ],
        ),
        migrations.CreateModel(
            name='Wall_finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='仕上 壁')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifcGUID', models.CharField(max_length=200, unique=True)),
                ('level', models.CharField(max_length=200, verbose_name='レベル')),
                ('No', models.CharField(max_length=200, unique=True, verbose_name='番号')),
                ('name', models.CharField(max_length=20, verbose_name='部屋名')),
                ('ceiling_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revitdb.ceiling_finish', verbose_name='仕上 天井')),
                ('floor_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revitdb.floor_finish', verbose_name='仕上 床')),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revitdb.project_info', verbose_name='プロジェクト名')),
                ('wall_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='revitdb.wall_finish', verbose_name='仕上 壁')),
            ],
        ),
    ]
