# Generated by Django 4.1.7 on 2023-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0004_ceiling_finish_floor_finish_wall_finish_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='No',
            field=models.CharField(max_length=200, unique=True, verbose_name='部屋番号'),
        ),
    ]
