# Generated by Django 4.1.7 on 2023-07-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0005_alter_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ifcGUID',
            new_name='IfcGUID',
        ),
    ]
