# Generated by Django 4.1.7 on 2023-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0006_rename_ifcguid_room_ifcguid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling_finish',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='仕上 天井'),
        ),
        migrations.AlterField(
            model_name='floor_finish',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='仕上 床'),
        ),
        migrations.AlterField(
            model_name='wall_finish',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='仕上 壁'),
        ),
    ]
