# Generated by Django 4.1.7 on 2023-08-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0007_alter_ceiling_finish_name_alter_floor_finish_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
