# Generated by Django 4.2.4 on 2023-08-04 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0009_remove_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='レベル名')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revitdb.level', verbose_name='レベル'),
        ),
    ]
