# Generated by Django 4.2.4 on 2023-08-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0009_remove_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='レベル')),
            ],
        ),
    ]
