# Generated by Django 4.2.4 on 2023-08-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revitdb', '0010_level_alter_room_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='No',
            field=models.CharField(max_length=200, verbose_name='部屋番号'),
        ),
    ]
